version: '3'

volumes:
  app-pgdata:

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.web.development
    volumes:
      - .:/home/appuser:delegated
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432"
    volumes:
      - app-pgdata:/var/lib/postgresql/data:delegated
